name: CI
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: [ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
      - name: Reclaim space
        uses: wimpysworld/nothing-but-nix@v6
        with:
          hatchet-protocol: rampage

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20

      - uses: cachix/cachix-action@v15
        with:
          name: slaier
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community

      - name: Build
        run: |
          env NIXPKGS_ALLOW_UNFREE=1 nix-build examples/simple --argstr device xiaomi-raphael -A outputs.android-fastboot-images
